### ISSUE TITLE
Progress bar for commit graph loading

### ISSUE THREAD

**Issue by colinwerner** [uvicgse/project-virtual-team-1#139]
Problem
When loading a new repo with a large commit history the commit graph can take a long time to draw.

Enhancement
Add a progress bar showing the progress in drawing the commit graph.

Alternatively, if loading the new repo is tied directly to drawing the graph, the progress bar could be for the repo loading progress.

**Comment by colinwerner** [comment]
Original Issue: https://github.com/uvicgse/project-seed/issues/53

**Comment by jerushachua** [comment]
Research task for sprint 4.

**Comment by sterlinglaird** [comment]
Perhaps is related to #122. From the testing I did the 1st zoom level is responsible for most of the performance issue for graph generation, so removal or reworking of that stage would solve this task. 

The enhancement of a progress bar instead of just a spinner would continue to help make things clearer however.
