### ISSUE TITLE
Clean up the open issues

### ISSUE THREAD

**Issue by colinwerner** [uvicgse/project-virtual-team-1#140]
Problem
The open issues have varying documentation quality.
Also, some of the open issues have been resolved.

Task
For each open issue in your teams repo, attempt to reproduce the issue.
If the issue no longer exists, close the issue with an informative comment.

If the issue is still outstanding, make sure the documentation is clear.
You will need to add to or modify the current documentation where appropriate.

This includes:

Modifying the issue title, if its too cryptic currently
Give a clear description of the issue
In the case of a bug, give clear steps to reproduce.
Provide screenshots

**Comment by colinwerner** [comment]
Original Issue: https://github.com/uvicgse/project-seed/issues/54

**Comment by hdauvic** [comment]
I'm going through, and only updating the open issues that are not currently tagged as being worked on by certain teams, or labeled with specific sprints. 

> is:open is:issue -label:"Sprint 5" -label:"Sprint 4" -label:"Sprint 3" -label:"Sprint 2" -label:"Sprint 1" -label:Group1 -label:Group2 -label:Group4

**Comment by hdauvic** [comment]
Awaiting help in reviewing a few issues, but otherwise the open issues have been combed through and reformatted for clarity and consistency. A wiki has been created with a summary of the changes: 
https://github.com/uvicgse/project-virtual-team-1/wiki/Updating-Issues    

Additionally, a wiki with formatting guidelines has been created for future issues:
https://github.com/uvicgse/project-virtual-team-1/wiki/Issue-Formatting-Guidelines
