### ISSUE TITLE
Redesign commit process with drag and drop feature 

### ISSUE THREAD

**Issue by omazhary** [uvicgse/project-virtual-team-1#38]
A redesign of the commit process involving dragging and dropping each individual file change to add them or remove them from each part of the process. This is as opposed to the current process of individually clicking on ones you want to keep. Each file change should be draggable and should have multiple ways of keeping or removing it from the actual commit.

**Comment by trstndvll** [comment]
There are a couple options we are looking into currently:
- HTML5 drag and drop support
- ng-drag-drop/ ng2-drag-drop Angular package via npm
- ng2-dnd, another package via npm

The challenges we need to solve so far include the fact that multiple files show up in div class="file" in file.panel.component.html and each need to be draggable independently, as well as the fact that we need to be able to have the stage and unstage functionality bidirectional, as you'll want to be able to stage and unstage back-and-forth.

We also want to keep the "stage all" and "unstage all" functionality to keep usability high.

![Screenshot 2019-06-07 20 25 23](https://user-images.githubusercontent.com/12837282/59141466-6a9d3a00-8962-11e9-82f0-6fd7526ad647.jpg)

**Comment by trstndvll** [comment]
Looking into HTML5 drag and dropping currently. If we set the file elements in the staging area to draggable, theoretically when we call an onDrop() function in file.panel.component.ts which then allows us to have an event to call the stage and unstage functions.

So instead of the .onclick functionality in git.ts we have .ondrop.
![Screenshot 2019-06-07 20 58 13](https://user-images.githubusercontent.com/12837282/59141728-3d9f5600-8967-11e9-94b1-30c87bab552f.jpg)

**Comment by trstndvll** [comment]
Current behaviour of staging and un-staging files
[https://youtu.be/ha_LUD6GNGU](url)

**Comment by trstndvll** [comment]
The Angular packages we were looking into (ng2-drag-drop, ng2-dragula, etc.) will not be feasible as they require dev dependencies that we cannot support. It looks like native HTML drag and drop along with JS will be the way to go. Currently looking into InteractJS to see if it is compatible with Angular2 and if it has features we could use.

**Comment by Unimax** [comment]
found prepareDontMissDND function in add.repository.component.ts file was causing repo to reload when we drop the dragged object.
Note: i think that part of the code contains errors. commenting it for now.

**Comment by Unimax** [comment]
created new branch **feature-38-drag-and-drop-without-angular-upgrade** and have committed implementation of the required feature using native HTML drag and drop feature.

I spend a hell lot of time trying to upgrade the angular dependencies to make ng2-dnd support. finally when I made our application work with the upgrades ( @ angular2.4.4). the ng2-dnd didn't work. the reason is not 100% clear to me. it was asking for DragAndDropService. but we are proving dynamic UI elements though TS. so I don't know how to fix that. so finally had to drop back to HTML based solution.

Parts left: highlight div where an item is getting dropped. increase the default size of those divs. and may be improved how each item CSS.

the application with upgraded angular2.4.4 still exits on the branch feature-38-drag-and-drop and could help in future if someone needs to upgrade angular. maybe could help in issue #24

**Comment by Unimax** [comment]
merged in #123 . Closing.
