### ISSUE TITLE
Allow a user to view current tags in current repo

### ISSUE THREAD

**Issue by colinwerner** [uvicgse/project-virtual-team-1#51]
This is a decomposition of #39.

view current tags in repo (git tag)

**Comment by sterlinglaird** [comment]
We can break this issue into 2 distinct tasks:

1. View optional textual data next to each commit. This is the UI component of this issue and would involve adding some way of viewing data for each commit. Since the text will be an optional tag, no additional text-box will appear if the data isn't available. The design of how this would be displayed would be part of this task.
2. Receiving tags from git. This is the back-end portion for interfacing directly with git.

Once both tasks are complete the UI elements can be linked to the tags that are received from git.

**Comment by colinwerner** [comment]
@sterlinglaird I believe this task is to show the results of running 'git tag' on the current branch. 

Showing the tags on each commit is #54.

**Comment by sterlinglaird** [comment]
When VisualGit queries for git references (to get branches), it gets all the tags as well. The system doesn't recognize that there is a difference between the 2 reference types so it currently displays all tags as branches in the GUI. We will need to parse the tags from the branches and keep a separate list of them so the GUI doesn't treat tags as branches.

**Comment by sterlinglaird** [comment]
@colinwerner I understand now, we didn't notice that was a follow-up task. We will add a drop-down list (like the branch list) for the tags present the repo.

**Comment by colinwerner** [comment]
@sterlinglaird interesting. I've never used tags in git before; however, it sounds like there is a.) a small bug to do and b.) a new feature to implement.

As you suggested, after performing the query we can separate them into branches and tags and add a new dropdown to show the tags?

Good investigation!

**Comment by sterlinglaird** [comment]
We have updated the branch dropdown to now contain tabs that can be used to switch between a list of branches and a list of tags in the repo. The search/create branch textbox doesn't do anything at the moment and was inactive before this change. We imagine this is a bug that will be addressed at some point. Currently clicking on a tag name does nothing, but in a following issue (#61) we will add support for checking out a tag just like a branch.

Here are the new branch and tag dropdown menus:
![branch](https://user-images.githubusercontent.com/13267819/58374135-7f52ea00-7eed-11e9-94b4-00dee21f2a9e.PNG) 
![tag](https://user-images.githubusercontent.com/13267819/58374136-837f0780-7eed-11e9-9c04-520ace4243b5.PNG)
