### ISSUE TITLE
Allow a user to see the tags on existing commits

### ISSUE THREAD

**Issue by colinwerner** [uvicgse/project-virtual-team-1#54]
This is a decomposition of #39.

showing existing tags associated with commits

**Comment by hdauvic** [comment]
Since this is associated with Issue #51 I started this issue once clarification was given. So far I've added in code framework to support the graphical GUI showing tags associated with each commit.
TODO:
- Create get all tags function, which is likely associated with Issue #52 
- figure out best console.log message to display tags along side commit id and message
- see how tags display in comparison to branches; branches have a short name utilized in the graph, will tags need the same?

**Comment by sterlinglaird** [comment]
Implemented in #84
